<!DOCTYPE html>
<html lang="vi">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php echo $this->headLink()->appendStylesheet('../public/css/admin/theme.css'); ?>
    <?php echo $this->headLink()->appendStylesheet('../public/css/admin/bootstrap.css'); ?>
    <?php echo $this->headLink()->appendStylesheet('../public/css/admin/font-face.css'); ?>
</head>

<body class="animsition">
<div class="page-wrapper">
    <div class="page-content--bge5">
        <div class="container">
            <div class="login-wrap">
                <?= $this->content ?>
            </div>
        </div>
    </div>

</div>
</body>
</html>





