<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;
use Entity\Users;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine Maping. Add your own custom
 * repository methods below.
 */
class UsersRepository extends CommonRepository
{

}
