<?php
date_default_timezone_set ( 'asia/ho_chi_minh' );
$date_time = date("d-m-Y H:i:s");
?>
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="panel panel-default">
            <div class="panel-heading">Them moi Topic</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="login-form">
                            <form action="/blog/admin/add-topic" method="post">
                                <div class="form-group">
                                    <label>Topic name</label>
                                    <input class="au-input au-input--full" type="text" name="topicname" placeholder="Topic name">
                                </div>
                                <div class="form-group">
                                    <label>Date</label>
                                    <input readonly class="au-input au-input--full" value="<?=$date_time?>"  type="text" name="date" placeholder="Date">
                                </div>
                                <div class="form-group">
                                    <input class="hidden au-input au-input--full" type="text" value="<?=$this->ac->getRole();?>" name="author" placeholder="Author">
                                </div>
                                <div class="form-group">
                                    <label>Content</label>
                                    <div class="nopadding">
                                        <textarea id="txtEditor"></textarea>
                                        <textarea id="txtEditorContent" class=" hidden au-input au-input--full"  name="content" placeholder="Content"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Avatar Topic</label>
                                    <input name="img-avatar" type="file" id="img-avatar">
                                </div>
                                <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">Them Topic</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>
