<?php
$user = $this->user;
?>
<div class="main-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <p>Ban chac muon xoa user: <?=$user->getName();?></p>
                <p>Email: <?=$user->getEmail();?></p>

                <form action="" method="POST">
                    <input type="submit" name="delete" value="No" class="btn btn-default">
                    <input type="submit" name="delete" value="Yes" class="btn btn-success">
                </form>
            </div>
        </div>
    </div>

</div>