

<?php
$title ="Danh sach Topic";
$this->headTitle($title);
?>
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="title-1 m-b-25 text-center">Danh sach Topic</h2>
                <div class="table-responsive table--no-card m-b-40">
                    <div class="au-task-list js-scrollbar3">
                        <?php
                        $stt=1;
                        foreach ($this->topic as $t):
                            $color = 'warning';
                            if($stt %2 ==0){
                                $color='success';
                            }
                            ?>
                            <div class="au-task__item au-task__item--<?=$color?>">
                                <div class="au-task__item-inner">
                                    <h5><?=$stt;?>./ <?=$t['name'];?>"</h5>
                                    <span class="time"><?=date_format($t['date'],'d/m/y');?></span>
                                    <p><?=$t['author'];?></p>
                                    <div class="option">
                                        <a href="<?=$this->url('admin',['action'=>'edit-topic','id'=>$t['id']]) ?>">Edit</a> |
                                        <a href="#">Delete</a>
                                    </div>
                                </div>

                            </div>
                            <?php
                            $stt++;
                        endforeach; ?>
                        <div class="au-task__footer">
                            <button class="au-btn au-btn-load js-load-btn">load more</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




