<?php
$title ="Danh sach User";
$this->headTitle($title);
?>
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="row">
    <div class="col-lg-12">
        <div class="text-center"><?=$this->flashMessenger()->render('success',['alert','alert-success','list-unstyled']);?></div>
        <h2 class="title-1 m-b-25 text-center">Danh sach user</h2>
        <div class="table-responsive table--no-card m-b-40">
            <table class="table table-borderless table-striped table-earning">
                <thead>
                <tr>
                    <th>STT</th>
                    <th>Ho Ten</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Option</th>
                </tr>
                </thead>
                <tbody>
                <?php
                $stt=1;
                foreach ($this->users as $user): ?>
                <tr>
                    <td><?=$stt;?></td>
                    <td><?=$user->getName();?></td>
                    <td><?=$user->getEmail();?></td>
                    <td><?=$user->getPhone();?></td>
                    <td>
                        <a href="<?=$this->url('admin',['action'=>'edit-user','id'=>$user->getId()]) ?>">Edit</a> |
                        <a href="<?=$this->url('admin',['action'=>'delete-user','id'=>$user->getId()]) ?>">Delete</a>
                    </td>
                </tr>
                <?php
                $stt++;
                endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
    </div>
</div>



